@UberEats.Api_HostAddress = http://localhost:5079
GET {{UberEats.Api_HostAddress}}/Dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMDg1MWU5MC1lZGY2LTQ5NjctOTdmMS0wNzVlNDJiZDJlNGMiLCJnaXZlbl9uYW1lIjoiYWpheWEgZGVlcCIsImZhbWlseV9uYW1lIjoic2hyZXN0aGEiLCJqdGkiOiI0ZWFmNzFiMi01NjA1LTQyMjktODMyOC04ZmI5MzZhNjJjZmQiLCJleHAiOjE3MTIyNzYzODgsImlzcyI6IlViZXJFYXRzIiwiYXVkIjoiVWJlckVhdHMifQ.hmFCTZtW3lIb0A-SGaIUlXR3mRjddO-Q2mozNBT4CAk
