@UberEats.Api_HostAddress = http://localhost:5079

POST {{UberEats.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  "firstname":"ajaya deep",
  "lastname":"shrestha",
  "email":"ajayadeepshrestha@gmail.com",
  "password":"tobeornottobe@12345!"
}
# {
#   "firstName":"",
#   "lastName":"",
#   "email":"",
#   "password":""
# }